### ISSUE TITLE
Questions : Anyone use jenkins/jenkins:2.256-centos7 Image can't use this plugin ?

### ISSUE THREAD

**Issue by winzaa123** [jenkinsci/discord-notifier-plugin#28]
I'm trying update version to **jenkins/jenkins:2.256-centos7**, but can't send discord webhook.

Now, I downgrade to **jenkins/jenkins:2.253-centos7**  work now.

**Comment by mightywomble** [comment]
Might be the same, i keep getting 
nz.co.jammehcow.jenkinsdiscord.exception.WebhookException: {"embeds": ["0"]}
	at nz.co.jammehcow.jenkinsdiscord.DiscordWebhook.send(DiscordWebhook.java:212)
	at nz.co.jammehcow.jenkinsdiscord.DiscordPipelineStep$DiscordPipelineStepExecution.run(DiscordPipelineStep.java:171)
	at nz.co.jammehcow.jenkinsdiscord.DiscordPipelineStep$DiscordPipelineStepExecution.run(DiscordPipelineStep.java:132)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate2(ACL.java:449)
	at hudson.security.ACL.impersonate(ACL.java:461)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
