### ISSUE TITLE
Plugin not working for maven jobs

### ISSUE THREAD

**Issue by Beelzebu** [jenkinsci/discord-notifier-plugin#3]
Hi, I was using version 1.1.0 of this plugin, today I uninstalled old version and installed the newest version from plugin manager and now the plugin isn't working for maven jobs, I tested it with a gradle job and worked fine.

**Jenkins version:** 2.138.3
**Plugin version:** 1.4.2
**Errors in console:**
```
ERROR: Build step failed with exception
java.lang.ClassCastException: hudson.maven.MavenModuleSet cannot be cast to hudson.model.Project
	at nz.co.jammehcow.jenkinsdiscord.WebhookPublisher.perform(WebhookPublisher.java:112)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.cleanUp(MavenModuleSetBuild.java:1098)
	at hudson.model.Run.execute(Run.java:1866)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Discord Notifier' marked build as failure
```

**Comment by Beelzebu** [comment]
Now it is showing this error for jobs that don't have a title configured
```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at nz.co.jammehcow.jenkinsdiscord.WebhookPublisher.perform(WebhookPublisher.java:117)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.cleanUp(MavenModuleSetBuild.java:1098)
	at hudson.model.Run.execute(Run.java:1866)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Discord Notifier' marked build as failure
```

**Comment by KocproZ** [comment]
Ok, try now and let me know if it works.

**Comment by Beelzebu** [comment]
It is working again, thanks!
